name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd app
          pnpm install

      - name: Debug environment
        run: |
          cd app
          echo "Node version: $(node -v)"
          echo "pnpm version: $(pnpm -v)"
          echo "List installed packages:"
          pnpm list
          echo "Object.keys polyfill check:"
          node -e "console.log('Object.keys exists:', typeof Object.keys === 'function')"
          echo "Object.values polyfill check:"
          node -e "console.log('Object.values exists:', typeof Object.values === 'function')"
          echo "Object.entries polyfill check:"
          node -e "console.log('Object.entries exists:', typeof Object.entries === 'function')"

      # Run specifically the muscles test first to focus on the issue
      - name: Run muscles test with detailed logs
        run: |
          cd app
          NODE_OPTIONS='--trace-warnings' pnpm vitest run src/lib/muscles.test.ts -v --no-threads
        continue-on-error: true

      # Display the failing test output directly in the log for easy access
      - name: Debug muscles.ts file content
        if: always()
        run: |
          cd app
          echo "============= muscles.ts content ============="
          cat src/lib/muscles.ts
          echo "============= muscles.ts file stats ============="
          stat src/lib/muscles.ts
          echo "============= Check muscles enum values ============="
          node -e "const { Muscles, musclesRegistry } = require('./src/lib/muscles.js'); console.log('Enum values:', Object.values(Muscles)); console.log('Registry keys:', Object.keys(musclesRegistry));"
        continue-on-error: true

      - name: Run only unit tests with details
        run: |
          cd app
          pnpm test:unit -v

      - name: Debug failing test
        if: failure()
        run: |
          cd app
          echo "Running specific failing test with more details:"
          pnpm vitest run src/lib/muscles.test.ts -v

      - name: Setup Playwright cache
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('app/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          cd app
          pnpm exec playwright install --with-deps chromium

      - name: Run tests in parallel
        run: |
          cd app
          pnpm test:parallel

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/test-results/
          retention-days: 7
